;#!/usr/bin/sbcl --script
;;;;   Hey, Emacs, this is a -*- Mode: Lisp; Syntax: Common-Lisp -*- file!
;;;;
;;;;   Lisp is the medium of choice for people who enjoy free style and flexibility.
;;;;   -- Gerald Jay Sussman
;;;;
;;;;   Name:               汉语.lisp
;;;;
;;;;   Started:            Sun May 11 13:52:10 2025
;;;;   Modifications:
;;;;
;;;;   Purpose:
;;;;
;;;;
;;;;
;;;;   Calling Sequence:
;;;;
;;;;
;;;;   Inputs:
;;;;
;;;;   Outputs:
;;;;
;;;;   Example:
;;;;
;;;;   Notes:
;;;;
;;;;
(load "/home/slytobias/lisp/packages/core")
(load "/home/slytobias/lisp/packages/io")
(load "/home/slytobias/lisp/packages/test")
(load "/home/slytobias/Thelio/modified/lisp/books/Tanimoto/2024/ch03/production-system.lisp")

(defpackage :汉语 (:use :common-lisp :core :io :test :production-system))

(in-package :汉语)

(defun 汉语 ()
  (let ((n nil)
        (s (make-string-output-stream)))
    (loop (if (null n)
              (setf n (get-num "Enter number: " :test (conjoin #'integerp (complement #'minusp))))
              (pscond ((> n 99)
                       (format t "太大.~%")
                       (setf n nil))
                      ((<= 91 n 99)
                       (format s "九十")
                       (decf n 90))
                      ((= n 90)
                       (format s "九十")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((<= 81 n 89)
                       (format s "八十")
                       (decf n 80))
                      ((= n 80)
                       (format s "八十")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((<= 71 n 79)
                       (format s "七十")
                       (decf n 70))
                      ((= n 70)
                       (format s "七十")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((<= 61 n 69)
                       (format s "六十")
                       (decf n 60))
                      ((= n 60)
                       (format s "六十")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((<= 51 n 59)
                       (format s "五十")
                       (decf n 50))
                      ((= n 50)
                       (format s "五十")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((<= 41 n 49)
                       (format s "四十")
                       (decf n 40))
                      ((= n 40)
                       (format s "四十")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((<= 31 n 39)
                       (format s "三十")
                       (decf n 30))
                      ((= n 30)
                       (format s "三十")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((<= 21 n 29)
                       (format s "二十")
                       (decf n 20))
                      ((= n 20)
                       (format s "二十")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((<= 11 n 19)
                       (format s "十")
                       (decf n 10))
                      ((= n 10)
                       (format s "十")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 9)
                       (format s "九")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 8)
                       (format s "八")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 7)
                       (format s "七")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 6)
                       (format s "六")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 5)
                       (format s "五")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 4)
                       (format s "四")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 3)
                       (format s "三")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 2)
                       (format s "二")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 1)
                       (format s "一")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 0)
                       (format s "零")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil)) )))) )

(defun 汉语1 ()
  (let ((n nil)
        (s (make-string-output-stream)))
    (loop (cond ((null n) (setf n (get-num "Enter number: " :test (conjoin #'integerp (complement #'minusp)))) )
                ;; ((zerop n)
                ;;  (format s "零")
                ;;  (format t "~A~%" (get-output-stream-string s))
                ;;  (setf n nil))
                (t (pscond ((> n 99)
                            (format t "太大.~%")
                            (setf n nil))
                           ((<= 90 n 99)
                            (format s "九十")
                            (decf n 90))
                           ((<= 80 n 89)
                            (format s "八十")
                            (decf n 80))
                           ((<= 70 n 79)
                            (format s "七十")
                            (decf n 70))
                           ((<= 60 n 69)
                            (format s "六十")
                            (decf n 60))
                           ((<= 50 n 59)
                            (format s "五十")
                            (decf n 50))
                           ((<= 40 n 49)
                            (format s "四十")
                            (decf n 40))
                           ((<= 30 n 39)
                            (format s "三十")
                            (decf n 30))
                           ((<= 20 n 29)
                            (format s "二十")
                            (decf n 20))
                           ((<= 10 n 19)
                            (format s "十")
                            (decf n 10))
                           ((= n 9)
                            (format s "九")
                            (decf n 9))
                           ((= n 8)
                            (format s "八")
                            (decf n 8))
                           ((= n 7)
                            (format s "七")
                            (decf n 7))
                           ((= n 6)
                            (format s "六")
                            (decf n 6))
                           ((= n 5)
                            (format s "五")
                            (decf n 5))
                           ((= n 4)
                            (format s "四")
                            (decf n 4))
                           ((= n 3)
                            (format s "三")
                            (decf n 3))
                           ((= n 2)
                            (format s "二")
                            (decf n 2))
                           ((= n 1)
                            (format s "一")
                            (decf n 1))
                           ((= n 0)
                            (format t "~A~%" (get-output-stream-string s))
                            (setf n nil)) )))) ))


                       
