;#!/usr/bin/sbcl --script
;;;;   Hey, Emacs, this is a -*- Mode: Lisp; Syntax: Common-Lisp -*- file!
;;;;
;;;;   Programming should be fun. Programs should be beautiful.
;;;;   -- Paul Graham
;;;;
;;;;   Name:               english.lisp
;;;;
;;;;   Started:            Sun May 11 13:45:04 2025
;;;;   Modifications:
;;;;
;;;;   Purpose:
;;;;
;;;;
;;;;
;;;;   Calling Sequence:
;;;;
;;;;
;;;;   Inputs:
;;;;
;;;;   Outputs:
;;;;
;;;;   Example:
;;;;
;;;;   Notes: Convert an integer between 0 and 99 into English text.
;;;;
;;;;
(load "/home/slytobias/lisp/packages/core.lisp")
(load "/home/slytobias/lisp/packages/io.lisp")
(load "/home/slytobias/lisp/books/Tanimoto/2024/ch03/production-system.lisp")

(defpackage :english (:use :common-lisp :core :io :production-system))

(in-package :english)

(defun english1 ()
  (let ((n nil)
        (s (make-string-output-stream)))
    (loop (if (null n)
              (setf n (get-num "Enter number: "
                               :test (conjoin #'integerp (complement #'minusp))))
              (pscond ((> n 99)
                       (format t "Too big.~%")
                       (setf n nil))
                      ((<= 91 n 99)
                       (format s "ninety-")
                       (decf n 90))
                      ((= n 90)
                       (format s "ninety")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((<= 81 n 89)
                       (format s "eighty-")
                       (decf n 80))
                      ((= n 80)
                       (format s "eighty")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((<= 71 n 79)
                       (format s "seventy-")
                       (decf n 70))
                      ((= n 70)
                       (format s "seventy")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((<= 61 n 69)
                       (format s "sixty-")
                       (decf n 60))
                      ((= n 60)
                       (format s "sixty")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((<= 51 n 59)
                       (format s "fifty-")
                       (decf n 50))
                      ((= n 50)
                       (format s "fifty")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((<= 41 n 49)
                       (format s "forty-")
                       (decf n 40))
                      ((= n 40)
                       (format s "forty")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((<= 31 n 39)
                       (format s "thirty-")
                       (decf n 30))
                      ((= n 30)
                       (format s "thirty")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((<= 21 n 29)
                       (format s "twenty-")
                       (decf n 20))
                      ((= n 20)
                       (format s "twenty")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 19)
                       (format s "nineteen")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 18)
                       (format s "eighteen")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 17)
                       (format s "seventeen")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 16)
                       (format s "sixteen")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 15)
                       (format s "fifteen")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 14)
                       (format s "fourteen")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 13)
                       (format s "thirteen")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 12)
                       (format s "twelve")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 11)
                       (format s "eleven")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 10)
                       (format s "ten")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 9)
                       (format s "nine")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 8)
                       (format s "eight")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 7)
                       (format s "seven")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 6)
                       (format s "six")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 5)
                       (format s "five")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 4)
                       (format s "four")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 3)
                       (format s "three")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 2)
                       (format s "two")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 1)
                       (format s "one")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil))
                      ((= n 0)
                       (format s "zero")
                       (format t "~A~%" (get-output-stream-string s))
                       (setf n nil)))) )))

(defun english-fp ()
  (labels ((process (n result)
             (pscond ((> n 999) (format t "Too big.~%"))
                     ((<= 901 n 999) (process (- n 900) (cons "nine hundred " result)))
                     ((= n 900) (cons "nine hundred" result))
                     ((<= 801 n 899) (process (- n 800) (cons "eight hundred " result)))
                     ((= n 800) (cons "eight hundred" result))
                     ((<= 701 n 799) (process (- n 700) (cons "seven hundred " result)))
                     ((= n 700) (cons "seven hundred" result))
                     ((<= 601 n 699) (process (- n 600) (cons "six hundred " result)))
                     ((= n 600) (cons "six hundred" result))
                     ((<= 501 n 599) (process (- n 500) (cons "five hundred " result)))
                     ((= n 500) (cons "five hundred" result))
                     ((<= 401 n 499) (process (- n 400) (cons "four hundred " result)))
                     ((= n 400) (cons "four hundred" result))
                     ((<= 301 n 399) (process (- n 300) (cons "three hundred " result)))
                     ((= n 300) (cons "three hundred" result))
                     ((<= 201 n 299) (process (- n 200) (cons "two hundred " result)))
                     ((= n 200) (cons "two hundred" result))
                     ((<= 101 n 199) (process (- n 100) (cons "one hundred " result)))
                     ((= n 100) (cons "one hundred" result))
                     ((<= 91 n 99) (process (- n 90) (cons "ninety-" result)))
                     ((= n 90) (cons "ninety" result))
                     ((<= 81 n 89) (process (- n 80) (cons "eighty-" result)))
                     ((= n 80) (cons "eighty" result))
                     ((<= 71 n 79) (process (- n 70) (cons "seventy-" result)))
                     ((= n 70) (cons "seventy" result))
                     ((<= 61 n 69) (process (- n 60) (cons "sixty-" result)))
                     ((= n 60) (cons "sixty" result))
                     ((<= 51 n 59) (process (- n 50) (cons "fifty-" result)))
                     ((= n 50) (cons "fifty" result))
                     ((<= 41 n 49) (process (- n 40) (cons "forty-" result)))
                     ((= n 40) (cons "forty" result))
                     ((<= 31 n 39) (process (- n 30) (cons "thirty-" result)))
                     ((= n 30) (cons "thirty" result))
                     ((<= 21 n 29) (process (- n 20) (cons "twenty-" result)))
                     ((= n 20) (cons "twenty" result))
                     ((= n 19) (cons "nineteen" result))
                     ((= n 18) (cons "eighteen" result))
                     ((= n 17) (cons "seventeen" result))
                     ((= n 16) (cons "sixteen" result))
                     ((= n 15) (cons "fifteen" result))
                     ((= n 14) (cons "fourteen" result))
                     ((= n 13) (cons "thirteen" result))
                     ((= n 12) (cons "twelve" result))
                     ((= n 11) (cons "eleven" result))
                     ((= n 10) (cons "ten" result))
                     ((= n 9) (cons "nine" result))
                     ((= n 8) (cons "eight" result))
                     ((= n 7) (cons "seven" result))
                     ((= n 6) (cons "six" result))
                     ((= n 5) (cons "five" result))
                     ((= n 4) (cons "four" result))
                     ((= n 3) (cons "three" result))
                     ((= n 2) (cons "two" result))
                     ((= n 1) (cons "one" result))
                     ((= n 0) (cons "zero" result)))) )
    (loop (let ((result (process (get-num "Enter number: "
                                          :test (conjoin #'integerp (complement #'minusp)))
                                 '())))
            (when result
              (format t "~A~%" (apply #'concatenate 'string (reverse result)))) ))))

(defun english-fp2 ()
  (labels ((process (n result)
             (pscond ((> n 999)
                      (format t "Too big.~%"))
                     ((and (> n 99) (zerop (mod n 100)))
                      (cons " hundred" (process (truncate n 100) result)))
                     ((> n 99)
                      (process (mod n 100) (cons " hundred " (process (truncate n 100) result))))
                     ((and (> n 19) (zerop (mod n 10)))
                      (cons (aref #("twenty" "thirty" "forty" "fifty" "sixty" "seventy" "eighty" "ninety") (- (truncate n 10) 2)) result))
                     ((> n 19)
;                      (process (mod n 10) (cons "-" (process (* (truncate n 10) 10) result))))
                      (process (mod n 10) (cons "-" (process (- n (mod n 10)) result))))
                     ((<= 0 n 19)
                      (cons (aref #("zero" "one" "two" "three" "four" "five" "six" "seven" "eight" "nine"
                                    "ten" "eleven" "twelve" "thirteen" "fourteen" "fifteen" "sixteen" "seventeen" "eighteen" "nineteen") n)
                            result)))) )
    (loop (let ((result (process (get-num "Enter number: "
                                          :test (conjoin #'integerp (complement #'minusp)))
                                 '())))
            (when result
              (format t "~A~%" (apply #'concatenate 'string (reverse result)))) ))))
